[package]
name = "wasm"
version = "0.1.0"
authors = ["Metacarft <atem@stormgate.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "^0.2"
diffy = "^0.2"
